# Generated by Django 4.2.17 on 2025-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='movies',
            name='exit_year',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='movies',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movies',
            name='synopsis',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(default='inconnu', max_length=35),
        ),
    ]
